[package]
name = "tauri-plugin-setapp"
version = "1.0.0"
authors = ["Nathan Lapierre"]
description = ""
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.5.1" }
cfg-if = "1.0"
