[package]
name = "tauri-plugin-setapp"
version = "2.0.0"
authors = ["Nathan Lapierre"]
description = ""
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "2" }
cfg-if = "1.0"
time = ">=0.3.35"
